# Generated by Django 2.0 on 2021-08-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='abc', max_length=255)),
                ('username', models.CharField(default='abc@012', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Image', models.ImageField(default='abc.jpg', upload_to='images/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
